### PR TITLE
Scheme LBTATools added to git repo to support carthage.

### PR DESCRIPTION
**Pull request by anesheret**
Added scheme to support carthage: using existing LBTATools scheme.

### CODE REVIEW

**Comment by anesheret** [comment]
@bhlvoong what about review my changes. I'm only add the LBTATools scheme to repo. This change is enough to cartage support.

**Comment by bhlvoong** [comment]
I'll have to learn how to use Carthage and confirm this patch works.

**Comment by bhlvoong** [comment]
I just modified the repo to support SPM.  Is carthage still necessary?

**Comment by flgadams** [comment]
Great! I don't use Carthage myself.

**Comment by anesheret** [comment]
Thanks, Carthage is not necessary now. PM is now enough.

**Pull request closed without merging**
